export const QUOTES = [
  `🔥 Functional chaos, quarterly aligned`,
  `Brain says nap 🧠, calendar says "Q4 deliverables."`,
  `Mission drift? Never heard of her. We pivot with grace.`,
  `Chaos: contained (with a stylish dashboard).`,
  `Energy report: ⚡ sporadic, but effective.`,
  `I opened my laptop to do one task. Now I'm rebranding.`,
  `🧠 Executive function booting… please wait`,
  `Status: buffering 🌀`,
  `Just one task. One simple- oh look, a rabbit hole.`,
  `"Start small" is cute until the spreadsheet has 14 tabs.`,
  `Overthinking = strategic foresight.`,
  `Brainstorming? More like brain-scattered 💥`,
  `📊 Gen Z + Performance Metrics = Me`,
  `KPIs met. Braincells? Unknown.`,
  `This isn't procrastination. It's cognitive prioritization 🧩`,
  `Inbox zero is a myth. I chase clarity, not perfection.`,
  `Half productivity, half ✨vibes✨.`,
  `Data-driven. Emotion-fueled. ADHD-powered.`,
  `🧃Vibe but make it scalable`,
  `I don't spiral—I iterate.`,
  `3 meetings, 2 crises, 1 iced coffee = Tuesday ☕`,
  `I'm multitasking on a molecular level.`,
  `"Strategic delay" > "procrastination." Say it with me.`,
  `If it's not in the calendar, it doesn't exist 📆`,
  `🦾 Systems girlie in her ops era`,
  `Attention span outsourced. Results? Still in-house.`,
  `Work smarter, not harder (but also overthink a bit).`,
  `Automate the boring, vibe through the rest 🤖`,
  `SOPs are just hyperfocus in documentation form.`,
  `My Asana board is therapy now.`,
  `📈 Results, but make it ✨neurospicy✨`,
  `I deliver. Eventually. Beautifully.`,
  `I built a workflow. Now I live in it.`,
  `My to-do list has a to-do list.`,
  `Deep dive = ADHD hyperfocus rebranded.`,
  `I don't miss deadlines. I reschedule deliverables.`,
  `🧠 ADHD-core with a 401(k)`,
  `"Why did you do it that way?" ✨Because it worked.✨`,
  `Innovation = I forgot the rulebook and made it better.`,
  `Delegation queen 👑 (because I will forget)`,
  `Notes app? No. Project management suite? Yes.`,
  `My brain is agile. My strategy is vibes-based.`,
  `🔮 Soft grit. Big moves.`,
  `Gentle structure > rigid systems.`,
  `One click, no fuss. One task, full send.`,
  `Progress isn't linear. It loops. Like my thoughts.`,
  `Clarity first. Then chaos. Then success.`,
  `ADHD sparkle ✨, aimed with intent.`,
  `💼 Slay at work, spiral at lunch`,
  `"Let's circle back" - me to my focus.`,
  `Work-life blend > work-life balance.`,
  `Burnout prevention is a deliverable, actually.`,
  `Peak performance? It's more of a vibe window.`,
  `Planning light so I can steer fast 🛞`,
  `🛠️ Corporate-coded ADHD toolkit`,
  `Task friction low. Dopamine access high.`,
  `Context ready. Action now.`,
  `Productivity ≠ hustle. It's precision.`,
  `Inbox muted, output loud.`,
  `Focus mode: kind of. Output? 🔥`,
];

export const getRotatingQuote = () => {
  const pick = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  // Normalize fancy dashes to hyphens to match house style
  return pick.replace(/\u2013|\u2014/g, "-");
};
